### ISSUE TITLE
Deadly aim (combat) feat

### ISSUE THREAD

**Issue by cyco-polo** [wildj79/foundryvtt-starfinder#581] opened 2022-04-03 17:02 UTC
[](https://user-images.githubusercontent.com/80625501/161438293-25a80d07-62df-420f-83f3-bd9e55ecf31c.png)[](https://user-images.githubusercontent.com/80625501/161438045-e53972ab-c688-4028-adbc-96bfeaa4df1a.png)Describe the bug
The feat "Deadly aim (combat)" has a dysfoncyion. I can't press any attack button...no reaction. But if i press on damage, i have a pop up appear normally and can even select deadly aim for damage

To Reproduce

Add the feat, click on any type of weapon, press attack...doesn't work

Expected behavior

to be able to initiate the attack roll

Screenshots

![Capture d’écran 2022-04-03 183611](https://user-images.githubusercontent.com/80625501/161439311-0db9ebd4-7b4f-4dd3-87cb-46d170afde36.png)

you can click "attaque" but nothing happens (tried with melee or other types of weapon with same result)

![Capture d’écran 2022-04-03 182707](https://user-images.githubusercontent.com/80625501/161439318-74e90110-ab33-42a0-873e-6349d090660d.png)

If you skip the attack and press "dommage" it works

Setup:

Foundry Version:9.255
System Version: Starfinder 0.18.2
Item Piles Version: [e.g. 1.0.0]
Browser & version Google Chrome Version 99.0.4844.84 (Build officiel) (64 bits)

**Comment by LebombJames** [comment] 2022-04-06 15:51
Can't reproduce this... Any errors in the console when you make an attack? (F12 -> Console)

**Comment by TheWoodenMan** [comment] 2022-06-12 09:29
This one appears to be fixed now.

When attached to a character sheet as a feat, deadly aim will show as a toggle on both the attack and damage roll pop-ups.

Attack
![image](https://user-images.githubusercontent.com/85075266/173226820-9bbd0cc0-8c0e-4cc9-8d89-ed4ed1d39fc3.png)

Damage
![image](https://user-images.githubusercontent.com/85075266/173226853-dfc21678-90e0-4b82-aaff-b6e2685e113b.png)

Effects are then shown on the attack/damage cards as normal:
![image](https://user-images.githubusercontent.com/85075266/173226899-24885b8c-8def-41e0-8427-93f9b0f7e21c.png)

**Comment by LebombJames** [comment] 2022-06-12 23:15
Sorry for leaving this so long, I thought the version in the compendium was already fixed. Changed the formula since `@attributes.bab` doesn't exist

**Closed** 2022-06-22 20:58 UTC
