### ISSUE TITLE
Spells use incorrect Melee Spell Attack and Ranged Spell Attack ability modifiers

### ISSUE THREAD

**Issue by ElroTheOnk** [wildj79/foundryvtt-starfinder#183] opened 2020-09-14 10:49 UTC
Foundry 0.6.6 & Starfinder 0.4.1.0, with no modules

Spells that are set up to use "Melee Spell Attack" or "Ranged Spell Attack" as their action type incorrectly gain a bonus of @abilities.int.mod instead of @abilities.str.mod or @abilities.dex.mod respectively. [Incorrect 5e pullthrough??]

Confirmed on Jolting Surge and Energy Ray as two relevant low-level core spells.

**Comment by wildj79** [comment] 2020-09-14 13:50
The spells are simply misconfigured. The "Ability Modifier" field under "Spell Effects" is set to a blank value, and it should be set to either Strength or Dexterity, depending on the type of attack you're supposed to be making.

**Comment by ElroTheOnk** [comment] 2020-09-14 17:53
Yep.
(I think) Under Starfinder, this should be the default behaviour for melee & ranged spell attacks respectively - would be best if the ability modifier field only needed to be set when something unusual was the case, I would have thought.

**Comment by wildj79** [comment] 2020-10-26 15:08
Though it does appear that we need to make a pass through the compendiums to make sure spells are setup correctly, and there is definitely a need for better (or any) documentation, I'm gonna go ahead and close this one. The fields are working as intended, they just weren't setup correctly.

**Closed by wildj79** 2020-10-26 15:08 UTC
Labels: needs documentation, wontfix
