### ISSUE TITLE
Roll Formula not working?

### ISSUE THREAD

**Issue by GreyAngelKing** [wildj79/foundryvtt-starfinder#165] opened 2020-08-25 20:59 UTC
Note: read through Closed issues saw something like this stated it was to go out in next release. release has happened since then so opening new issue
I cant Get Roll Formulas to work for modifiers for adding a d6 for my players Envoy expertise skill Am i doing something wrong?

Have tried

+1d6
1d6
d6
/r 1d6
ends up just adding a value (usually) six to the stat

**Comment by wildj79** [comment] 2020-08-25 21:16
How are you trying to add it. Some more detail here will be helpful.

**Comment by wildj79** [comment] 2020-08-25 21:43
Yep, looks like this isn't working as intended for skills.

**Comment by GreyAngelKing** [comment] 2020-08-25 21:54
Im trying to add it in  Passive Envoy class feature Expertise Adding a new modifier specific skill, Roll Formula. oddly have noted that changing the type of bonus (insight base untyped ect) changes the value it adds but not consistently bonus decreases till the bonus disappears entirely.

Also of interest to note Toggling the modifier on and off Causes a random bonus value within the confines of the roll formula to be added as a static bonus to the roll. I think its Rolling the formula once upon saving or turning the modifier on and applying that bonus to the roll as a static value.  Hope that helps solve the problem

**Comment by wildj79** [comment] 2020-08-25 22:08
![](https://github.trello.services/images/mini-trello-icon.png) [[BUGZ] Roll formula's not working for skill modifiers](https://trello.com/c/yGA0Hwo0/60-bugz-roll-formulas-not-working-for-skill-modifiers)

**Comment by wildj79** [comment] 2020-08-26 17:36
This has been fixed and will be included in the next release.

**Closed by wildj79** 2020-08-26 17:36 UTC
