### ISSUE TITLE
character sheet unusable in 0.8.5 version 

### ISSUE THREAD

**Issue by Artalo** [wildj79/foundryvtt-starfinder#395] opened 2021-05-30 05:16 UTC
when updating foundry to version 0.8.5 all character sheets stopped working.
otherwise it seems to work without problems.

**Comment by TimToxopeus** [comment] 2021-05-30 17:21
Refreshing the window probably resolves it for you.

However, this issue is known, I just pushed a fix for it, I hope it is the proper fix as the cause of the issue was somewhat nebulous and there was no proper error in the console.

**Closed by TimToxopeus** 2021-05-30 17:21 UTC
