### ISSUE TITLE
Modifiers don't work on the Drone Sheet

### ISSUE THREAD

**Issue by mxvs** [wildj79/foundryvtt-starfinder#133] opened 2020-08-09 11:02 UTC
Steps to reproduce:

1. Create a drone sheet
2. Add any modifier either directly on the sheet or through an item or feat. Easy to test is AC.
3. Notice how modifiers don't change the values they are supposed to modify.

**Comment by TimToxopeus** [comment] 2020-08-09 11:08
It is currently difficult for me to test because I'm on the development branch, but it is working fine for me there.
Which version of the system are you on? There is a bug in 0.3.4 that prevented drone calculations from functioning, but this has been patched since 0.3.5.

Also, did you add a chassis to your drone?

**Comment by TimToxopeus** [comment] 2020-08-09 11:14
Aha yes, I see some modifiers don't work, AC and Hitpoints, for example. Ability Scores, Saving Throws, and Skill modifiers seem to work as intended.

**Comment by TimToxopeus** [comment] 2020-08-09 16:46
Submitted a fix for AC, HP, and RP, will be available upon the next release.

**Comment by wildj79** [comment] 2020-08-23 22:15
Fixed in the latest release.

**Closed by wildj79** 2020-08-23 22:15 UTC
