### ISSUE TITLE
Consumable Usage doesn't work

### ISSUE THREAD

**Issue by reubzilla** [wildj79/foundryvtt-starfinder#356] opened 2021-04-01 01:38 UTC
When using a consumable like a serum of healing it doesn't consume on use or destroy when empty as indicated on the item details tab. When nesting several of the same item (again serum of healing) the amount doesn't go down on usage.

**Comment by wildj79** [comment] 2021-12-28 15:05
Seems like these became broken a few updates ago. They partially work, but they are definitely not working as intended.

**Comment by TimToxopeus** [comment] 2022-01-16 15:14
This should be fixed in the next update.

**Closed by TimToxopeus** 2022-01-16 15:14 UTC
Labels: bug
